// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoBry9y5mFbacz0lmiol7hlMaGQ7frpVk',
    appId: '1:534687188611:web:287ae003d7e84b07247db6',
    messagingSenderId: '534687188611',
    projectId: 'chatapp-e672a',
    authDomain: 'chatapp-e672a.firebaseapp.com',
    storageBucket: 'chatapp-e672a.firebasestorage.app',
    measurementId: 'G-5GCL6M5TG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41na3fwik-DBHVJNpkePuO12PRLTvkN4',
    appId: '1:534687188611:android:6aa5734d7172cde1247db6',
    messagingSenderId: '534687188611',
    projectId: 'chatapp-e672a',
    storageBucket: 'chatapp-e672a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrBxCw30_XAlQEqlBSFi1Y2LKy0JrsMuI',
    appId: '1:534687188611:ios:7ecd82d4fdbd613b247db6',
    messagingSenderId: '534687188611',
    projectId: 'chatapp-e672a',
    storageBucket: 'chatapp-e672a.firebasestorage.app',
    iosBundleId: 'com.example.thoughtbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrBxCw30_XAlQEqlBSFi1Y2LKy0JrsMuI',
    appId: '1:534687188611:ios:7ecd82d4fdbd613b247db6',
    messagingSenderId: '534687188611',
    projectId: 'chatapp-e672a',
    storageBucket: 'chatapp-e672a.firebasestorage.app',
    iosBundleId: 'com.example.thoughtbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoBry9y5mFbacz0lmiol7hlMaGQ7frpVk',
    appId: '1:534687188611:web:d3df28c8b19a5f57247db6',
    messagingSenderId: '534687188611',
    projectId: 'chatapp-e672a',
    authDomain: 'chatapp-e672a.firebaseapp.com',
    storageBucket: 'chatapp-e672a.firebasestorage.app',
    measurementId: 'G-T4Q70X3Z3R',
  );
}
